
---
- hosts: localhost
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install required packages
          apt:
            name:
              - bat
              - jq
            state: present
